### ISSUE TITLE
`lbh-label` is overriding label modifiers

### ISSUE THREAD

**Issue by sirLisko** [LBHackney-IT/lbh-frontend#147]
**Describe the bug**

`lbh-label` is overriding all the label modifiers (i.e. `govuk-label--xl`).

The problem is visible in the docs 👇 

https://design-system.hackney.gov.uk/components/label

**How it looks at the moment**:

<img width="831" alt="Screenshot 2021-03-19 at 12 57 33" src="https://user-images.githubusercontent.com/435399/111784166-5ae2b180-88bb-11eb-97b0-2bcd3ac0a375.png">

**How it should look:**

<img width="833" alt="Screenshot 2021-03-19 at 12 58 21" src="https://user-images.githubusercontent.com/435399/111784210-69c96400-88bb-11eb-9ccc-1bc4a58969d9.png">

**Comment by jhackett1** [comment]
working on this
