### ISSUE TITLE
Add a variant of the button size

### ISSUE THREAD

**Issue by sirLisko** [LBHackney-IT/lbh-frontend#151]
Ideally, we want to be able to define a button with the same height as the inputs.

<img width="597" alt="Screenshot 2021-03-19 at 15 27 34" src="https://user-images.githubusercontent.com/435399/111804169-1d3c5380-88d0-11eb-9aef-b6304dc8e3cd.png">

I don't know if our buttons should adapt to the same height of the inputs or if it's better to add a new button modifier, for example `lbh-button--s`.

**Comment by jhackett1** [comment]
i normally use a wrapper with `display: flex` to accomplish this - force it to stretch the children to fit the right height

would also be curious whether there's a larger pattern we could take/reuse from it

**Comment by sirLisko** [comment]
`disaply: flex` won't solve the problem, as the button `line-height` is not adapting :disappointed:

<img width="553" alt="Screenshot 2021-03-19 at 16 13 15" src="https://user-images.githubusercontent.com/435399/111998739-99c37200-8b1c-11eb-8a9f-07eceeb47ff7.png">
