### ISSUE TITLE
Add hint as component.

### ISSUE THREAD

**Issue by LBHELewis** [LBHackney-IT/LBH-frontend#34]

**Comment by LBHELewis** [comment]
@erbridge @CJWaszczuk I was thinking about this last night and understood better why the hint (and the tag) was never added to our pattern library. This is because the hint is only ever included inside other components (radios / select lists etc), and they are components for which we are simply importing the govuk template. This means we are unable to replace the inner component (hint, tag) with our own. So instead of creating a hint component that would never be used, I wrote a mixin in the core sass files that could then be included for any govuk-hint inside our components (i.e. `. lbh-radios .govuk-hint`). Does that make sense? On this basis I'm not sure whether or not it makes sense to include the hint as a component in the non-react pattern library directly as it will never be used. What do you think?

**Comment by erbridge** [comment]
I think that makes sense. What do you do about users wanting to use hint text outside of one of those components? Like adding hint text under the heading in a `fieldset`?

**Comment by LBHELewis** [comment]
Well at the moment alongside the mixin in `core/_hint.scss` (https://github.com/LBHackney-IT/LBH-frontend/blob/master/src/lbh/core/_hint.scss) has a property selector that includes the mixin for any hint inside a `.lbh-form-group` class, so a govuk-hint should look correct so long as it's within a form group and that core sass file is being included. I guess it'd probably be best to create our own version of the hint which would only get used in those instances? I just didn't want to create a hint that isn't used and then have people confused about the hint they see in radios (for example) not being the lbh-hint.

**Comment by erbridge** [comment]
I see what you're saying. I think this is only as confusing as [`govuk-frontend` is in this regard](https://github.com/alphagov/govuk-frontend/tree/master/src/govuk/components/hint), though, right?

**Comment by LBHELewis** [comment]
Decision: create Hint component. Will aim to get done next week.

**Comment by erbridge** [comment]
Amazing. Thanks.

**Comment by erbridge** [comment]
I think if you used the same approach as we have in #41, you'd be able to share the styles with templates that have deeply nested hints without having to eject all of the templates, and clear up some of the nested styling.

**Comment by LBHELewis** [comment]
@erbridge @CJWaszczuk Hint now added as component https://github.com/LBHackney-IT/LBH-frontend/pull/46
