### ISSUE TITLE
Consider using a changelog

### ISSUE THREAD

**Issue by erbridge** [LBHackney-IT/LBH-frontend#36]
As a package depending on this package, it would be really helpful to know what changes have gone into a new version. I suggest using a [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format changelog, which you update as you make the changes. Any thoughts?

**Comment by LBHELewis** [comment]
Yes definitely - it's been on my list of things to do and now that we're a live package I need to get it in place, thanks for the reminder.

**Comment by LBHELewis** [comment]
Changelog added: https://github.com/LBHackney-IT/LBH-frontend/pull/37

There are already a Changelog template here: https://github.com/LBHackney-IT/LBH-frontend/blob/master/docs/contributing/CHANGELOG_TEMPLATE.md

**Comment by erbridge** [comment]
👍
