### ISSUE TITLE
Consider relaxing restrictions around using NVM

### ISSUE THREAD

**Issue by erbridge** [LBHackney-IT/LBH-frontend#42]
There are other Node environment managers (N, Nodenv, probably more). What matters is the version of Node that's running, not whether someone is using NVM to run it.

**Comment by erbridge** [comment]
I can put in a quick PR for this if you think it's a good idea.

**Comment by LBHELewis** [comment]
That's a really good idea, thank you - if you could put in a PR that'd be amazing.

**Comment by erbridge** [comment]
I'll take a look.
