### ISSUE TITLE
core/_form-group.scss does not import the govuk-form-group styles

### ISSUE THREAD

**Issue by CJWaszczuk** [LBHackney-IT/LBH-frontend#49]
`lbh-frontend-react` is going to require a FormGroup component in order to correctly group form controls. I was looking for the form group styling and I found a file inside core, but it does not import the core govuk-form-group styles inside it. I'm assuming this may be because the styles can be imported from the components where form-group is being used.

I would need both this file and the govuk file seperately imported. The ideal would be to import the `lbh-frontend` form-group and have that import the `govuk-frontend` styles.

**Comment by CJWaszczuk** [comment]
[PR](https://github.com/LBHackney-IT/LBH-frontend/pull/54) opened with changes

**Comment by LBHELewis** [comment]
I've merged the PR, will go in with the next release.

**Comment by erbridge** [comment]
When are you planning on releasing the next version? We have a PR waiting for this on `lbh-frontend-react`.

**Comment by LBHELewis** [comment]
@erbridge I've just released v1.5 which contains this change.

**Comment by erbridge** [comment]
Great. Thanks!
