### ISSUE TITLE
_width-container.scss contains no import for govuk-width-contaner mixin.

### ISSUE THREAD

**Issue by CJWaszczuk** [LBHackney-IT/LBH-frontend#55]
An error occurs when importing [lbh-container](https://github.com/LBHackney-IT/LBH-frontend/blob/master/src/lbh/objects/_width-container.scss) from lbh-frontend, needs an import for the `govuk-width-container` mixin.

**Comment by LBHELewis** [comment]
Fixed and ready for next release.

**Comment by LBHELewis** [comment]
Released in 1.6.0
