### ISSUE TITLE
Primary and secondary buttons have different heights 

### ISSUE THREAD

**Issue by CJWaszczuk** [LBHackney-IT/LBH-frontend#69]
**Screenshot**
<img width="1090" alt="Screenshot 2019-12-18 at 13 39 51" src="https://user-images.githubusercontent.com/8092247/71090891-f0b0fd80-219b-11ea-8755-e051cc70e959.png">

**Comment by LBHELewis** [comment]
Fixed here: https://github.com/LBHackney-IT/LBH-frontend/pull/75
